################################################################
# Global configuration
################################################################
traefikLogsFile = "log/traefik.log"
[accessLog]
  Filename = "log/access.log"
  Brokers = "173.39.246.177:31092"
  Topic = "traefik"
logLevel = "DEBUG"

################################################################
# Web configuration backend
################################################################
[web]
address = ":7888"

################################################################
# File configuration backend
################################################################
[file]

################################################################
# rules
################################################################
 [backends]
   [backends.backend1]
     [backends.backend1.servers.server1]
       url = "http://127.0.0.1:8081"
   [backends.backend2]
     [backends.backend2.LoadBalancer]
       method = "drr"
     [backends.backend2.servers.server1]
       url = "http://127.0.0.1:8082"
     [backends.backend2.servers.server2]
       url = "http://127.0.0.1:8083"
  [frontends]
   [frontends.david-staging--traefik-kafka-3--traefik-kafka-cmx-3--807e8c]
   backend = "backend1"
     [frontends.david-staging--traefik-kafka-3--traefik-kafka-cmx-3--807e8c.routes.test_1]
     rule = "Path: /test1"
   [frontends.testenv--hello-world--hello-php--7bf184]
   backend = "backend2"
   passHostHeader = true
     [frontends.testenv--hello-world--hello-php--7bf184.routes.test_2]
     rule = "Path: /test2"